amazon:
  access:
    key: AKIA3AVURT6XTADLKJER
    secret-key: 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
  region: us-east-1
  end-point:
    url: dynamodb.us-east-1.amazonaws.com
server:
  port: 9001